name: Noticias Diarias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
    - cron: '0 15 * * *'

jobs:
  enviar-noticia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install requests feedparser
      - name: Correr script
        run: python noticias.py
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
